train_dataset: mini-imagenet
train_dataset_args: {split: train}
tval_dataset: mini-imagenet
tval_dataset_args: {split: test}
val_dataset: mini-imagenet
val_dataset_args: {split: val}

model: meta-baseline
model_args: 
#    encoder: resnet12
    encoder: Jelly_resnet12
    encoder_args: {}
load_encoder: ./save/classifier_mini-imagenet_Jelly_resnet12_2way_RBF_CKA/max-va.pth


n_way: 2
n_shot: 5
n_query: 15
#train_batches: 16
#ep_per_batch: 4

train_batches: 200
train_ep_per_batch: 1

training_batch: 25

val_batches: 30
val_ep_per_batch: 24

max_epoch: 40
optimizer: sgd
#optimizer: adam
optimizer_args: {lr: 0.001, weight_decay: 5.e-4}

visualize_datasets: True

