train_dataset: omniglot
train_dataset_args: {split: train, augment: resize}
#val_dataset: omniglot
#val_dataset_args: {split: train_phase_val}
fs_dataset: omniglot
fs_dataset_args: {split: test}
eval_fs_epoch: 1

model: classifier
model_args:
#    encoder: resnet12
    encoder: Jelly_convnet4
    encoder_args: {}
    classifier: linear-classifier
    classifier_args: {n_classes: 1200}

n_ways: [2, 5, 20]
n_query: 15
n_shots: [1, 5]
ep_per_batchs: [16, 8, 1]

batch_size: 32
max_epoch: 1000
optimizer: sgd
#optimizer: adam
optimizer_args: {lr: 0.05, weight_decay: 5.e-4, milestones: [90, 125]}

save_epoch: 5
visualize_datasets: true
