train_dataset: tiered-imagenet
train_dataset_args: {split: train, augment: resize}
val_dataset: tiered-imagenet
val_dataset_args: {split: val}
fs_dataset: tiered-imagenet
fs_dataset_args: {split: test}
eval_fs_epoch: 5

model: classifier
model_args:
#    encoder: resnet12
    encoder: Jelly_resnet12
    encoder_args: {}
    classifier: linear-classifier
    classifier_args: {n_classes: 351}

n_way: 2
n_query: 15
n_shots: [1, 5]

batch_size: 64
max_epoch: 140
optimizer: sgd
optimizer_args: {lr: 0.05, weight_decay: 5.e-4, milestones: [40, 80]}

save_epoch: 5
visualize_datasets: true
