train_dataset: tiered-imagenet
train_dataset_args: {split: train}
tval_dataset: tiered-imagenet
tval_dataset_args: {split: test}
val_dataset: tiered-imagenet
val_dataset_args: {split: val}

model: meta-baseline
model_args: 
#    encoder: resnet12
    encoder: Jelly_resnet12
    encoder_args: {}
load_encoder: ./save/classifier_tiered-imagenet_Jelly_resnet12_2way_RBF_CKA/max-va.pth

n_way: 2
n_shot: 5
n_query: 15
#train_batches: 16
#ep_per_batch: 4

train_batches: 64
train_ep_per_batch: 1

training_batch: 25

val_batches: 30  # n_way=2: 30, 5: 60, 10: 120
val_ep_per_batch: 24  # n_way=2: 24, 5: 12, 10: 6

max_epoch: 40
optimizer: sgd
optimizer_args: {lr: 0.001, weight_decay: 5.e-4}

visualize_datasets: True
